Ast separation review
performantdata/sangria pull request #3
Opened 2021-11-04 09:37 UTC by yanns

2021-11-04 10:20 UTC, performantdata requested changes
Looks fine, if it makes you happy. Still, I doubt anyone's using it directly.

2021-11-04 10:20 UTC, performantdata commented on build.sbt
> -
The blank line was there to signal the end of the related comment:
```scala
// changed `Some` return to `Option`:
```

2021-11-04 10:20 UTC, performantdata commented on modules/core/src/test/scala/sangria/util/GraphQlSupport.scala
> +import sangria.parser.{QueryParser, SourceMapper}
Not sure why you're changing this, since you're deprecating the `parser` version.

2021-11-04 10:22 UTC, yanns commented on modules/core/src/test/scala/sangria/util/GraphQlSupport.scala
> +import sangria.parser.{QueryParser, SourceMapper}
to make sure that it's working

2021-11-04 10:23 UTC, yanns commented
> Looks fine, if it makes you happy. Still, I doubt anyone's using it directly.

By trying a snapshot version, I had a lot of compilation errors because of `SourceMapper` that is being used on any custom validation using `AstNodeViolation` .

2021-11-04 10:23 UTC, performantdata commented
I incorporated a couple of your changes in my branch before I realized that you're actually PR-ing to it, so you'll need to rebase.

2021-11-04 10:25 UTC, yanns commented on build.sbt
> -
scalafmt did that

2021-11-04 10:27 UTC, yanns commented
> I incorporated a couple of your changes in my branch before I realized that you're actually PR-ing to it, so you'll need to rebase.

You could aslo remove some commits in your branch, force-push, and then merge this one.

2021-11-04 10:28 UTC, performantdata commented on build.sbt
> -
Hm. Scalafmt didn't complain when I checked that in. It must not be being run on this file in CI. I don't automatically scalafmt on save.

2021-11-04 10:57 UTC, yanns commented
@performantdata I'll create another PR.

2021-11-04 10:57 UTC, closed without merging

2021-11-04 11:15 UTC, yanns commented
@performantdata I won't have time today. If you want, you can cherry-pick some commits, and just create your own with copy/pasta.

2021-11-04 18:54 UTC, performantdata commented on modules/core/src/test/scala/sangria/util/GraphQlSupport.scala
> +import sangria.parser.{QueryParser, SourceMapper}
We can revert now?
```
[warn] /home/runner/work/sangria/sangria/modules/core/src/test/scala/sangria/util/GraphQlSupport.scala:190:21: type SourceMapper in package parser is deprecated (since 3.0.0): please use `sangria.ast.SourceMapper`
[warn]       sourceMapper: Option[SourceMapper],
[warn]                     ^
[warn] /home/runner/work/sangria/sangria/modules/core/src/test/scala/sangria/util/GraphQlSupport.scala:188:14: type SourceMapper in package parser is deprecated (since 3.0.0): please use `sangria.ast.SourceMapper`
[warn]   case class StubViolation(
[warn]              ^
```

2021-11-05 06:33 UTC, yanns commented on modules/core/src/test/scala/sangria/util/GraphQlSupport.scala
> +import sangria.parser.{QueryParser, SourceMapper}
If we want to propose backwards compatibility with deprecations like this, we can also test it. Maybe it should be better to add a new test for it though.

2021-11-05 14:59 UTC, performantdata commented on modules/core/src/test/scala/sangria/util/GraphQlSupport.scala
> +import sangria.parser.{QueryParser, SourceMapper}
Not sure how to write a test for that. Reflection?

2021-11-05 15:09 UTC, performantdata commented on modules/core/src/test/scala/sangria/util/GraphQlSupport.scala
> +import sangria.parser.{QueryParser, SourceMapper}
nvm, this thread moved [here](https://github.com/sangria-graphql/sangria/pull/777#discussion_r743429781)